export const FETCH_GROUPS = 'FETCH_GROUPS';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT = 'LOGOUT';
export const PULL_AUTH_FROM_STORAGE = 'PULL_AUTH_FROM_STORAGE';
export const UPDATE_CURRENT_USER_NAME = 'UPDATE_CURRENT_USER_NAME';

export default {
  FETCH_GROUPS,
  LOGIN_USER,
  LOGOUT,
  PULL_AUTH_FROM_STORAGE,
  UPDATE_CURRENT_USER_NAME,
};
