export const ADD_GROUP_INVITATION = 'ADD_GROUP_INVITATION';
export const ADD_USER_TO_GROUP = 'ADD_USER_TO_GROUP';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const DELETE_GROUP_INVITATION = 'DELETE_GROUP_INVITATION';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT = 'LOGOUT';
export const PULL_AUTH_FROM_STORAGE = 'PULL_AUTH_FROM_STORAGE';
export const SET_ERROR = 'SET_ERROR';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const UPDATE_ALL_GROUP_INVITATIONS = 'UPDATE_ALL_GROUP_INVITATIONS';
export const UPDATE_ALL_GROUPS = 'UPDATE_ALL_GROUPS';
export const UPDATE_CURRENT_USER_NAME = 'UPDATE_CURRENT_USER_NAME';
export const UPDATE_GROUP = 'UPDATE_GROUP';

export default {
  ADD_GROUP_INVITATION,
  ADD_USER_TO_GROUP,
  CLEAR_ERRORS,
  DELETE_GROUP_INVITATION,
  LOGIN_USER,
  LOGOUT,
  PULL_AUTH_FROM_STORAGE,
  SET_ERROR,
  SET_ERROR_MESSAGE,
  UPDATE_ALL_GROUP_INVITATIONS,
  UPDATE_ALL_GROUPS,
  UPDATE_CURRENT_USER_NAME,
  UPDATE_GROUP,
};
